language: node_js
node_js:
- v8
- v10
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
script:
  - npm test -- -i --coverage
env:
  global:
  - CXX=g++-4.8
  - MASTER_KEY=masterKey
  - JWT_SECRET=jwtSecret
